rules:
  indentation:
    - 1
    -
      size: 4
  no-trailing-whitespace: 0
  final-newline: 0
  property-sort-order: 0
   nesting-depth:
    - 1
    - max-depth: 4
  class-name-format:
    - 1
    -
      convention: hyphenatedbem